! =============================================================================
! FORTRAN SIGNAL CONVOLVER
! AUTHOR : ANUBHAV MATTOO
! DATE : 6TH NOVEMBER 2021
! =============================================================================

MODULE CONVOLVER
IMPLICIT NONE
PRIVATE
PUBLIC :: CONVOLVE
CONTAINS
	FUNCTION CONVOLVE(SIGNAL_INPUT, IMPLUSE_RESPONSE) RESULT(SIGNAL_OUTPUT)
	IMPLICIT NONE
	REAL, INTENT(IN) :: SIGNAL_INPUT(:), IMPLUSE_RESPONSE(:)
	REAL :: SIGNAL_OUTPUT(1:SIZE(SIGNAL_INPUT)+SIZE(IMPLUSE_RESPONSE))
		INTEGER :: I, J
		DO I = 1, SIZE(SIGNAL_INPUT)
			DO J = 1, SIZE(IMPLUSE_RESPONSE)
				SIGNAL_OUTPUT(I+J) = SIGNAL_OUTPUT(I+J) &
				                   + SIGNAL_INPUT(I) * IMPLUSE_RESPONSE(J)
			END DO
		END DO
	END FUNCTION CONVOLVE
END MODULE CONVOLVER