! =============================================================================
! LINEAR EQUATION SOLVER WITH GAUSSIAN ELEMINATION
! =============================================================================

SUBROUTINE MATRIX_PRINTER(MATRIX, N)
! MATRIX PRETTY PRINTER
IMPLICIT NONE
REAL, DIMENSION(1:N, 1:N+1), INTENT(IN) :: MATRIX
INTEGER, INTENT(IN) :: N
	INTEGER :: I, J
	WRITE(*, *)
	DO I = 1, N
		WRITE(*, 150, ADVANCE='NO') MATRIX(I, 1)
		DO J = 2, N
			WRITE(*, 151, ADVANCE='NO') MATRIX(I, J)
		END DO
		WRITE(*, 152) MATRIX(I, N+1)
	END DO
	WRITE(*, *)
150 FORMAT('|', (F10.4), ', ')
151 FORMAT((F10.4), ', ')
152 FORMAT((F10.4), '|')
END SUBROUTINE MATRIX_PRINTER

SUBROUTINE MATRIX_READER(MATRIX, N)
! MATRIX READER
IMPLICIT NONE
REAL, DIMENSION(1:N, 1:N+1), INTENT(INOUT) :: MATRIX
INTEGER, INTENT(IN) :: N
	INTEGER :: I, J
	DO I = 1, N
		DO J = 1, N+1
			WRITE(*, 153, ADVANCE='NO') I, J  
			READ(*, *) MATRIX(I, J)
		END DO
	END DO
153 FORMAT('AUG_MAT[', (I3), ', ' (I3), '] = ')
END SUBROUTINE MATRIX_READER

SUBROUTINE ROW_SCANNER(MATRIX, N)
! SWAPS ROWS WITH A[I, I] = 0.0 TO OTHER ROWS IF AVAILABLE
IMPLICIT NONE
REAL, DIMENSION(1:N, 1:N+1), INTENT(INOUT) :: MATRIX
INTEGER, INTENT(IN) :: N
	REAL, DIMENSION(1:N+1) :: TEMP
	INTEGER :: I, J
	DO I = 1, N
		IF (MATRIX(I, I) /= 0.0) CYCLE
		DO J = I+1, N
			IF (MATRIX(J, J) /= 0.0) THEN
				TEMP = MATRIX(I, :)
				MATRIX(I, :) = MATRIX(J, :)
				MATRIX(J, :) = TEMP
			END IF
		END DO
	END DO
END SUBROUTINE ROW_SCANNER

SUBROUTINE ROW_ECHELON(MATRIX, N)
! CONVERTS THE AUGMENTED MATRIX OF THE SYSTEM
! TO THE ROW ECHELON FORM TO 
IMPLICIT NONE
REAL, DIMENSION(1:N, 1:N+1), INTENT(INOUT) :: MATRIX
INTEGER, INTENT(IN) :: N
	INTEGER :: I, J, K
	REAL :: RATIO
	CALL ROW_SCANNER(MATRIX, N)
	DO I = 1, N
		DO J = I+1, N
			! NAIVE DIV0 MITIGATION
			IF (MATRIX(I, I) == 0) CYCLE
			RATIO = MATRIX(J, I) / MATRIX(I, I)
			DO K = I, N+1
				MATRIX(J, K) = MATRIX(J, K) - RATIO * MATRIX(I, K)
			END DO
		END DO		
	END DO
END SUBROUTINE ROW_ECHELON

SUBROUTINE BACK_SUBSTITUTION(MATRIX, N, X)
IMPLICIT NONE
REAL, INTENT(OUT) :: X(1:N)
REAL, DIMENSION(1:N, 1:N+1), INTENT(IN) :: MATRIX
INTEGER, INTENT(IN) :: N
	INTEGER :: I, J
	X(N) = MATRIX(N, N+1) / MATRIX(N, N)
	DO I = N-1, 1, -1
		X(I) = MATRIX(I, N+1)
		DO J = I+1, N+1
			X(I) = X(I) - MATRIX(I, J) * X(J)
		END DO
		X(I) = X(I) / MATRIX(I, I)
	END DO
	RETURN
END SUBROUTINE BACK_SUBSTITUTION

PROGRAM GAUSSIAN_SOLVER
IMPLICIT NONE
	INTEGER :: N, I
	REAL, DIMENSION(:, :), ALLOCATABLE :: AUG_MAT
	REAL, DIMENSION(:), ALLOCATABLE :: X
	WRITE(*, '(A)', ADVANCE='NO') "ENTER THE NUMBER OF UNKNOWNS : "
	READ(*, '(I3)') N
	ALLOCATE(AUG_MAT(1:N, 1:N+1))
	ALLOCATE(X(1:N))
	CALL MATRIX_READER(AUG_MAT, N)
	CALL MATRIX_PRINTER(AUG_MAT, N)
	CALL ROW_ECHELON(AUG_MAT, N)
	CALL MATRIX_PRINTER(AUG_MAT, N)
	CALL BACK_SUBSTITUTION(AUG_MAT, N, X)
	DO I = 1, N
		WRITE(*, 154) I, X(I)
	END DO
154 FORMAT('X[', (I3), '] = ', (F10.4))
END PROGRAM GAUSSIAN_SOLVER