MODULE INTEGER_LIST_M
    IMPLICIT NONE
    PRIVATE
    PUBLIC :: INTEGER_LIST_T, VISITOR_T

    TYPE :: LIST_NODE_T
        PRIVATE
        INTEGER :: VAL
        TYPE(LIST_NODE_T), POINTER :: NEXT => NULL()
    END TYPE

    TYPE :: INTEGER_LIST_T
        PRIVATE
        TYPE(LIST_NODE_T), POINTER :: HEAD => NULL()
    CONTAINS
        PRIVATE
        PROCEDURE, PUBLIC :: PREPEND
        PROCEDURE, PUBLIC :: FOREACH
    END TYPE

    TYPE, ABSTRACT :: VISITOR_T
    CONTAINS
        PRIVATE
        PROCEDURE(VISIT_I), DEFERRED, PUBLIC :: VISIT
    END TYPE

    ABSTRACT INTERFACE
        SUBROUTINE VISIT_I(SELF, ITEM)
            IMPORT VISITOR_T
            IMPLICIT NONE
            CLASS(VISITOR_T), INTENT(INOUT) :: SELF
            INTEGER, INTENT(INOUT) :: ITEM
        END SUBROUTINE
    END INTERFACE
CONTAINS
    SUBROUTINE PREPEND(SELF, ITEM)
        CLASS(INTEGER_LIST_T), INTENT(INOUT) :: SELF
        INTEGER, INTENT(IN) :: ITEM

        TYPE(LIST_NODE_T), POINTER :: NEW

        IF (ASSOCIATED(SELF%HEAD)) THEN
            ALLOCATE(NEW)
            NEW%VAL = ITEM
            NEW%NEXT => SELF%HEAD
            SELF%HEAD => NEW
        ELSE
            ALLOCATE(SELF%HEAD)
            SELF%HEAD%VAL = ITEM
        END IF
    END SUBROUTINE

    SUBROUTINE FOREACH(SELF, VISITOR)
        CLASS(INTEGER_LIST_T), INTENT(INOUT) :: SELF
        CLASS(VISITOR_T), INTENT(INOUT) :: VISITOR

        TYPE(LIST_NODE_T), POINTER :: CURSOR

        CURSOR => SELF%HEAD
        DO WHILE (ASSOCIATED(CURSOR))
            CALL VISITOR%VISIT(CURSOR%VAL)
            CURSOR => CURSOR%NEXT
        END DO
    END SUBROUTINE
END MODULE

MODULE LIST_OPERATOR_M
    USE INTEGER_LIST_M, ONLY: VISITOR_T

    IMPLICIT NONE
    PRIVATE
    PUBLIC :: PRINTER_T, SQUARER_T

    TYPE, EXTENDS(VISITOR_T) :: PRINTER_T
    CONTAINS
        PRIVATE
        PROCEDURE, PUBLIC :: VISIT => PRINTER_VISIT
    END TYPE

    TYPE, EXTENDS(VISITOR_T) :: SQUARER_T
    CONTAINS
        PRIVATE
        PROCEDURE, PUBLIC :: VISIT => SQUARER_VISIT
    END TYPE
CONTAINS
    SUBROUTINE PRINTER_VISIT(SELF, ITEM)
        CLASS(PRINTER_T), INTENT(INOUT) :: SELF
        INTEGER, INTENT(INOUT) :: ITEM

        PRINT *, ITEM
    END SUBROUTINE

    SUBROUTINE SQUARER_VISIT(SELF, ITEM)
        CLASS(SQUARER_T), INTENT(INOUT) :: SELF
        INTEGER, INTENT(INOUT) :: ITEM

        ITEM = ITEM*ITEM
    END SUBROUTINE
END MODULE

PROGRAM MAIN
    USE INTEGER_LIST_M, ONLY: INTEGER_LIST_T
    USE LIST_OPERATOR_M, ONLY: PRINTER_T, SQUARER_T

    IMPLICIT NONE

    TYPE(INTEGER_LIST_T) :: LIST
    TYPE(PRINTER_T) :: PRINTER
    TYPE(SQUARER_T) :: SQUARER
    ! TYPE(SUMMER_T) :: SUMMER

    CALL LIST%PREPEND(2)
    CALL LIST%PREPEND(3)
    CALL LIST%PREPEND(5)

    CALL LIST%FOREACH(PRINTER)

    CALL LIST%FOREACH(SQUARER)

    CALL LIST%FOREACH(PRINTER)

    ! CALL LIST%FOREACH(SUMMER)
    ! PRINT *, SUMMER%GET_SUM()
END PROGRAM
